

from PyQt5 import QtCore, QtGui, QtWidgets
from YolcuBilgi import Yolcu
import sqlite3

class Sefer(object):

    def load(self):

        conn = sqlite3.connect('Data.db')
        content = 'SELECT * FROM NIKE'
        result = conn.execute(content)
        self.tableWidget.setRowCount(0)
        for row_number, row_data in enumerate(result):
            self.tableWidget.insertRow(row_number)
            for colm_number, data in enumerate(row_data):
                self.tableWidget.setItem(row_number, colm_number, QtWidgets.QTableWidgetItem(str(data)))
        conn.close()

    def delete(self):
        conn = sqlite3.connect('Data.db')
        curs = conn.cursor()
        msgbox = QtWidgets.QMessageBox()
        msgbox.setInformativeText('Your ticket has been deleted')
        content = 'SELECT * FROM NIKE'
        res = curs.execute(content)
        for row in enumerate(res):
            if row[0] == self.tableWidget.currentRow():
                data = row[1]
                name = data[0]
                color = data[1]
                date = data[2]
                departure = data[3]
                arrive = data[4]
                price = data[5]
                gender = data[6]
                seat = data[7]
                curs.execute(''' DELETE FROM NIKE WHERE NAME=? AND COLOR=? AND DATE=? AND DEPARTURE=? 
                AND ARRIVAL=? AND PRICE=? AND 
                GENDER=? AND SEAT=?''', (name, color, date, departure, arrive, price, seat, gender))
                conn.commit()
                msgbox.exec()
                self.load()





    def add(self):
        name=self.textEdit_2.toPlainText()
        color = self.textEdit_3.toPlainText()
        date = self.textEdit.toPlainText()
        msgbox = QtWidgets.QMessageBox()
        conn = sqlite3.connect('Data.db')
        conn.execute(''' INSERT INTO NIKE(DEPARTURE,ARRIVAL,PRICE) VALUES(?, ?, ?)''', (name,color, date))
        conn.commit()
        msgbox.setInformativeText('Your ticket information has been saved, you can cancel your ticket before proceeding to payment and passenger information.')
        self.load()
        msgbox.exec()

    def load(self):

        conn = sqlite3.connect('Data.db')
        content = 'SELECT * FROM NIKE'
        result = conn.execute(content)
        self.tableWidget.setRowCount(0)
        for row_number, row_data in enumerate(result):
            self.tableWidget.insertRow(row_number)
            for colm_number, data in enumerate(row_data):
                self.tableWidget.setItem(row_number, colm_number, QtWidgets.QTableWidgetItem(str(data)))
        conn.close()
    def M(self):
        self.new8 = QtWidgets.QMainWindow()
        self.ui = Yolcu()
        self.ui.setupUi(self.new8)
        self.new8.show()
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1069, 603)
        font = QtGui.QFont()
        font.setPointSize(10)
        Form.setFont(font)
        Form.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(0, 290, 47, 51))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("../../Pictures/Camera Roll/Screenshot_17.png"))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(250, 300, 47, 41))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: rgb(0, 85, 255);")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(250, 370, 47, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: rgb(0, 85, 255);")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(90, 370, 47, 13))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color: rgb(0, 85, 255);")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setGeometry(QtCore.QRect(90, 310, 47, 13))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("color: rgb(0, 85, 255);")
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(Form)
        self.label_6.setGeometry(QtCore.QRect(170, 310, 47, 13))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("color: rgb(0, 85, 255);")
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(Form)
        self.label_7.setGeometry(QtCore.QRect(170, 420, 47, 13))
        self.label_7.setStyleSheet("color: rgb(0, 85, 255);")
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(Form)
        self.label_8.setGeometry(QtCore.QRect(170, 370, 47, 13))
        self.label_8.setStyleSheet("color: rgb(0, 85, 255);")
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(Form)
        self.label_9.setGeometry(QtCore.QRect(170, 470, 47, 13))
        self.label_9.setStyleSheet("color: rgb(0, 85, 255);")
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(Form)
        self.label_10.setGeometry(QtCore.QRect(260, 420, 47, 13))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setStyleSheet("color: rgb(0, 85, 255);")
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(Form)
        self.label_11.setGeometry(QtCore.QRect(90, 470, 47, 13))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setStyleSheet("color: rgb(0, 85, 255);")
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(Form)
        self.label_12.setGeometry(QtCore.QRect(90, 420, 47, 13))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_12.setFont(font)
        self.label_12.setStyleSheet("color: rgb(0, 85, 255);")
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(Form)
        self.label_13.setGeometry(QtCore.QRect(260, 470, 47, 13))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_13.setFont(font)
        self.label_13.setStyleSheet("color: rgb(0, 85, 255);")
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(Form)
        self.label_14.setGeometry(QtCore.QRect(0, 360, 47, 31))
        self.label_14.setText("")
        self.label_14.setPixmap(QtGui.QPixmap("../../Pictures/Camera Roll/Screenshot_17.png"))
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(Form)
        self.label_15.setGeometry(QtCore.QRect(0, 410, 47, 31))
        self.label_15.setText("")
        self.label_15.setPixmap(QtGui.QPixmap("../../Pictures/Camera Roll/Screenshot_17.png"))
        self.label_15.setObjectName("label_15")
        self.label_16 = QtWidgets.QLabel(Form)
        self.label_16.setGeometry(QtCore.QRect(0, 460, 47, 41))
        self.label_16.setText("")
        self.label_16.setPixmap(QtGui.QPixmap("../../Pictures/Camera Roll/Screenshot_17.png"))
        self.label_16.setObjectName("label_16")
        self.checkBox = QtWidgets.QCheckBox(Form)
        self.checkBox.setGeometry(QtCore.QRect(370, 300, 70, 17))
        self.checkBox.setStyleSheet("color: rgb(0, 85, 255);")
        self.checkBox.setObjectName("checkBox")
        self.checkBox_2 = QtWidgets.QCheckBox(Form)
        self.checkBox_2.setGeometry(QtCore.QRect(500, 300, 70, 17))
        self.checkBox_2.setStyleSheet("color: rgb(0, 85, 255);")
        self.checkBox_2.setObjectName("checkBox_2")
        self.checkBox_3 = QtWidgets.QCheckBox(Form)
        self.checkBox_3.setGeometry(QtCore.QRect(640, 300, 70, 17))
        self.checkBox_3.setStyleSheet("color: rgb(0, 85, 255);")
        self.checkBox_3.setObjectName("checkBox_3")
        self.checkBox_4 = QtWidgets.QCheckBox(Form)
        self.checkBox_4.setGeometry(QtCore.QRect(370, 360, 70, 17))
        self.checkBox_4.setStyleSheet("color: rgb(0, 85, 255);")
        self.checkBox_4.setObjectName("checkBox_4")
        self.checkBox_5 = QtWidgets.QCheckBox(Form)
        self.checkBox_5.setGeometry(QtCore.QRect(510, 360, 70, 17))
        self.checkBox_5.setStyleSheet("color: rgb(0, 85, 255);")
        self.checkBox_5.setObjectName("checkBox_5")
        self.checkBox_6 = QtWidgets.QCheckBox(Form)
        self.checkBox_6.setGeometry(QtCore.QRect(640, 360, 70, 17))
        self.checkBox_6.setStyleSheet("color: rgb(0, 85, 255);")
        self.checkBox_6.setObjectName("checkBox_6")
        self.checkBox_7 = QtWidgets.QCheckBox(Form)
        self.checkBox_7.setGeometry(QtCore.QRect(510, 460, 70, 17))
        self.checkBox_7.setStyleSheet("color: rgb(0, 85, 255);")
        self.checkBox_7.setObjectName("checkBox_7")
        self.checkBox_8 = QtWidgets.QCheckBox(Form)
        self.checkBox_8.setGeometry(QtCore.QRect(370, 460, 70, 17))
        self.checkBox_8.setStyleSheet("color: rgb(0, 85, 255);")
        self.checkBox_8.setObjectName("checkBox_8")
        self.checkBox_9 = QtWidgets.QCheckBox(Form)
        self.checkBox_9.setGeometry(QtCore.QRect(640, 410, 70, 17))
        self.checkBox_9.setStyleSheet("color: rgb(0, 85, 255);")
        self.checkBox_9.setObjectName("checkBox_9")
        self.checkBox_10 = QtWidgets.QCheckBox(Form)
        self.checkBox_10.setGeometry(QtCore.QRect(510, 410, 70, 17))
        self.checkBox_10.setStyleSheet("color: rgb(0, 85, 255);")
        self.checkBox_10.setObjectName("checkBox_10")
        self.checkBox_11 = QtWidgets.QCheckBox(Form)
        self.checkBox_11.setGeometry(QtCore.QRect(370, 410, 70, 17))
        self.checkBox_11.setStyleSheet("color: rgb(0, 85, 255);")
        self.checkBox_11.setObjectName("checkBox_11")
        self.checkBox_12 = QtWidgets.QCheckBox(Form)
        self.checkBox_12.setGeometry(QtCore.QRect(640, 460, 70, 17))
        self.checkBox_12.setStyleSheet("color: rgb(0, 85, 255);")
        self.checkBox_12.setObjectName("checkBox_12")
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(960, 540, 91, 51))
        self.pushButton.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.pushButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("fotoğraf/icons8-right-arrow-144.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon)
        self.pushButton.setIconSize(QtCore.QSize(32, 32))
        self.pushButton.setObjectName("pushButton")
        self.pushButton.clicked.connect(self.M)
        self.pushButton_2 = QtWidgets.QPushButton(Form)
        self.pushButton_2.setGeometry(QtCore.QRect(10, 540, 91, 51))
        self.pushButton_2.setStyleSheet("color: rgb(0, 85, 255);")
        self.pushButton_2.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("fotoğraf/icons8-left-arrow-144.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_2.setIcon(icon1)
        self.pushButton_2.setIconSize(QtCore.QSize(32, 32))
        self.pushButton_2.setObjectName("pushButton_2")
        self.label_23 = QtWidgets.QLabel(Form)
        self.label_23.setGeometry(QtCore.QRect(90, 240, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_23.setFont(font)
        self.label_23.setStyleSheet("color: rgb(85, 85, 255);\n"
"color: rgb(0, 85, 255);")
        self.label_23.setObjectName("label_23")
        self.label_24 = QtWidgets.QLabel(Form)
        self.label_24.setGeometry(QtCore.QRect(370, 240, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_24.setFont(font)
        self.label_24.setStyleSheet("color: rgb(85, 85, 255);\n"
"color: rgb(0, 85, 255);")
        self.label_24.setObjectName("label_24")
        self.label_25 = QtWidgets.QLabel(Form)
        self.label_25.setGeometry(QtCore.QRect(250, 240, 51, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_25.setFont(font)
        self.label_25.setStyleSheet("color: rgb(85, 85, 255);\n"
"color: rgb(0, 85, 255);")
        self.label_25.setObjectName("label_25")
        self.label_26 = QtWidgets.QLabel(Form)
        self.label_26.setGeometry(QtCore.QRect(500, 240, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_26.setFont(font)
        self.label_26.setStyleSheet("color: rgb(85, 85, 255);\n"
"color: rgb(0, 85, 255);")
        self.label_26.setObjectName("label_26")
        self.label_27 = QtWidgets.QLabel(Form)
        self.label_27.setGeometry(QtCore.QRect(640, 240, 51, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_27.setFont(font)
        self.label_27.setStyleSheet("color: rgb(85, 85, 255);\n"
"color: rgb(0, 85, 255);")
        self.label_27.setObjectName("label_27")
        self.frame = QtWidgets.QFrame(Form)
        self.frame.setGeometry(QtCore.QRect(0, 10, 191, 101))
        self.frame.setStyleSheet("image: url(:/newPrefix/fotoğraf/images.jpg);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label_17 = QtWidgets.QLabel(Form)
        self.label_17.setGeometry(QtCore.QRect(240, 95, 331, 91))
        font = QtGui.QFont()
        font.setFamily("HoloLens MDL2 Assets")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_17.setFont(font)
        self.label_17.setStyleSheet("color: rgb(0, 85, 255);")
        self.label_17.setObjectName("label_17")
        self.tableWidget = QtWidgets.QTableWidget(Form)
        self.tableWidget.setGeometry(QtCore.QRect(800, 260, 256, 192))
        self.tableWidget.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(8)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(7, item)
        self.textEdit = QtWidgets.QTextEdit(Form)
        self.textEdit.setGeometry(QtCore.QRect(850, 180, 181, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.textEdit.setFont(font)
        self.textEdit.setStyleSheet("QTextEdit{\n"
"\n"
"background:transparent;\n"
"border:none;\n"
"    \n"
"    \n"
"    color: rgb(85, 170, 255);\n"
"border-bottom:1px solid #717072\n"
"}\n"
"")
        self.textEdit.setObjectName("textEdit")
        self.textEdit_2 = QtWidgets.QTextEdit(Form)
        self.textEdit_2.setGeometry(QtCore.QRect(850, 40, 181, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.textEdit_2.setFont(font)
        self.textEdit_2.setStyleSheet("QTextEdit{\n"
"\n"
"background:transparent;\n"
"border:none;\n"
"    \n"
"    \n"
"    color: rgb(85, 170, 255);\n"
"border-bottom:1px solid #717072\n"
"}\n"
"")
        self.textEdit_2.setObjectName("textEdit_2")
        self.textEdit_3 = QtWidgets.QTextEdit(Form)
        self.textEdit_3.setGeometry(QtCore.QRect(850, 110, 181, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.textEdit_3.setFont(font)
        self.textEdit_3.setStyleSheet("QTextEdit{\n"
"\n"
"background:transparent;\n"
"border:none;\n"
"    \n"
"    \n"
"    color: rgb(85, 170, 255);\n"
"border-bottom:1px solid #717072\n"
"}\n"
"")
        self.textEdit_3.setObjectName("textEdit_3")
        self.pushButton_3 = QtWidgets.QPushButton(Form)
        self.pushButton_3.setGeometry(QtCore.QRect(770, 480, 75, 23))
        msgbox = QtWidgets.QMessageBox()
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setItalic(True)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setStyleSheet("QPushButton{\n"
"color: rgb(85, 170, 255);\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(18, 97, 200);\n"
"}")
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_3.clicked.connect(self.add)
        self.pushButton_4 = QtWidgets.QPushButton(Form)
        self.pushButton_4.setGeometry(QtCore.QRect(860, 480, 101, 23))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setItalic(True)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setStyleSheet("QPushButton{\n"
"color: rgb(85, 170, 255);\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(18, 97, 200);\n"
"}")
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_4.clicked.connect(self.load)
        self.pushButton_5 = QtWidgets.QPushButton(Form)
        self.pushButton_5.setGeometry(QtCore.QRect(974, 480, 91, 23))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setItalic(True)
        self.pushButton_5.setFont(font)
        self.pushButton_5.setStyleSheet("QPushButton{\n"
"color: rgb(85, 170, 255);\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(18, 97, 200);\n"
"}")
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_5.clicked.connect(self.delete)
        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_2.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:9pt;\">10.00</span></p></body></html>"))
        self.label_3.setText(_translate("Form", "15.00"))
        self.label_4.setText(_translate("Form", "13.00"))
        self.label_5.setText(_translate("Form", "08.00"))
        self.label_6.setText(_translate("Form", "-----------"))
        self.label_7.setText(_translate("Form", "------------"))
        self.label_8.setText(_translate("Form", "------------"))
        self.label_9.setText(_translate("Form", "------------"))
        self.label_10.setText(_translate("Form", "20.00"))
        self.label_11.setText(_translate("Form", "23.00"))
        self.label_12.setText(_translate("Form", "16.00"))
        self.label_13.setText(_translate("Form", "04.00"))
        self.checkBox.setText(_translate("Form", "90.00₺"))
        self.checkBox_2.setText(_translate("Form", "100.00₺"))
        self.checkBox_3.setText(_translate("Form", "120.00₺"))
        self.checkBox_4.setText(_translate("Form", "100.00₺"))
        self.checkBox_5.setText(_translate("Form", "110.00₺"))
        self.checkBox_6.setText(_translate("Form", "130.00₺"))
        self.checkBox_7.setText(_translate("Form", "140.00₺"))
        self.checkBox_8.setText(_translate("Form", "120.00₺"))
        self.checkBox_9.setText(_translate("Form", "150.00₺"))
        self.checkBox_10.setText(_translate("Form", "130.00₺"))
        self.checkBox_11.setText(_translate("Form", "110.00₺"))
        self.checkBox_12.setText(_translate("Form", "160.00₺"))
        self.label_23.setText(_translate("Form", "Departure"))
        self.label_24.setText(_translate("Form", "Normal Line"))
        self.label_25.setText(_translate("Form", "Arrival"))
        self.label_26.setText(_translate("Form", "Long Line"))
        self.label_27.setText(_translate("Form", "Jumbo"))
        self.label_17.setText(_translate("Form", "                     SELECT DEPARTURE TIME"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Form", "WHERE"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Form", "WHERE FROM"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("Form", "DATE"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("Form", "DEPARTURE"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("Form", "ARRIVAL"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("Form", "PRICE"))
        item = self.tableWidget.horizontalHeaderItem(6)
        item.setText(_translate("Form", "SEAT NO"))
        item = self.tableWidget.horizontalHeaderItem(7)
        item.setText(_translate("Form", "GENDER"))
        self.textEdit.setPlaceholderText(_translate("Form", "PRICE"))
        self.textEdit_2.setPlaceholderText(_translate("Form", "DEPARTURE"))
        self.textEdit_3.setPlaceholderText(_translate("Form", "ARRIVAL"))
        self.pushButton_3.setText(_translate("Form", "ADD TICKET"))
        self.pushButton_4.setText(_translate("Form", "DİSPLAY TICKET"))
        self.pushButton_5.setText(_translate("Form", "DELETE TICKET"))

import test2

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Sefer()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())

